#!/usr/bin/env python3
"""
CLAWBOT Backtest Runner
========================
Automates MT5 Strategy Tester execution via CLI configuration.
Launches MT5 in tester mode, waits for completion, and parses results.
"""

import os
import sys
import time
import subprocess
from pathlib import Path
from datetime import datetime, timedelta


# Report filenames generated by the CLAWBOT audit module
AUDIT_REPORT = "CLAWBOT_Backtest_Report.csv"
AUDIT_PASS   = "CLAWBOT_Pass_Report.csv"
AUDIT_WEAK   = "CLAWBOT_Weakness_Report.csv"
MT5_REPORT   = "CLAWBOT_Backtest.htm"


def generate_tester_config(
    config_template: Path,
    output_path: Path,
    login: str = "0",
    password: str = "",
    server: str = "Deriv-Demo",
    symbol: str = "XAUUSD",
    period: str = "H1",
    from_date: str = None,
    to_date: str = None,
    deposit: int = 10000,
    leverage: int = 100,
) -> Path:
    """
    Generate a filled MT5 tester configuration INI from the template.
    Returns the path to the generated config file.
    """
    # Default: 2 years of data ending today
    if to_date is None:
        to_date = datetime.now().strftime("%Y.%m.%d")
    if from_date is None:
        two_years_ago = datetime.now() - timedelta(days=730)
        from_date = two_years_ago.strftime("%Y.%m.%d")

    # Read template
    template = config_template.read_text()

    # Fill placeholders
    config = template.format(
        login=login,
        password=password,
        server=server,
        symbol=symbol,
        period=period,
        from_date=from_date,
        to_date=to_date,
        deposit=deposit,
        leverage=leverage,
    )

    # Write filled config
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(config)

    return output_path


def find_report_files(data_path: Path) -> dict:
    """
    Search for CLAWBOT report files in the MT5 data directory.
    The EA writes reports to MQL5/Files/CLAWBOT_Reports/
    """
    files_dir = data_path / "MQL5" / "Files" / "CLAWBOT_Reports"
    tester_dir = data_path / "Tester"

    found = {}

    # EA-generated audit reports (CSV)
    for name, key in [
        (AUDIT_REPORT, "audit_report"),
        (AUDIT_PASS, "pass_report"),
        (AUDIT_WEAK, "weakness_report"),
    ]:
        path = files_dir / name
        if path.exists():
            found[key] = path

    # MT5-generated HTML report
    if tester_dir.exists():
        for htm_file in tester_dir.rglob("CLAWBOT*.htm"):
            found["mt5_report"] = htm_file
            break

    # Also check the report path specified in tester config
    report_dir = data_path / "CLAWBOT_Reports"
    if report_dir.exists():
        for csv_file in report_dir.glob("*.csv"):
            if "Pass" in csv_file.name:
                found["pass_report"] = csv_file
            elif "Weakness" in csv_file.name:
                found["weakness_report"] = csv_file
            elif "Backtest" in csv_file.name:
                found["audit_report"] = csv_file

    return found


def clean_old_reports(data_path: Path):
    """Remove old CLAWBOT report files to ensure fresh results."""
    files_dir = data_path / "MQL5" / "Files" / "CLAWBOT_Reports"
    if files_dir.exists():
        for f in files_dir.glob("CLAWBOT_*.csv"):
            try:
                f.unlink()
                print(f"  [CLEAN] Removed old report: {f.name}")
            except OSError:
                pass


def is_mt5_running() -> bool:
    """Check if MT5 terminal is currently running."""
    try:
        result = subprocess.run(
            ["tasklist", "/FI", "IMAGENAME eq terminal64.exe"],
            capture_output=True, text=True, timeout=10
        )
        return "terminal64.exe" in result.stdout.lower()
    except Exception:
        return False


def wait_for_mt5_close(timeout_minutes: int = 120) -> bool:
    """
    Wait for MT5 to finish the backtest and close.
    MT5 auto-closes when ShutdownTerminal=1 is set in tester config.
    """
    print(f"  Waiting for backtest to complete (timeout: {timeout_minutes} min)...")
    print("  [TIP] You can monitor progress in the MT5 Strategy Tester window.")

    start = time.time()
    timeout_sec = timeout_minutes * 60
    last_dot = start

    # Wait for MT5 to start first (give it 30 seconds)
    for _ in range(30):
        if is_mt5_running():
            break
        time.sleep(1)
    else:
        print("  [WARNING] MT5 did not appear to start. It may have exited immediately.")
        return True  # Check for reports anyway

    # Now wait for it to close
    while time.time() - start < timeout_sec:
        if not is_mt5_running():
            elapsed = int(time.time() - start)
            print(f"\n  [OK] MT5 closed after {elapsed // 60}m {elapsed % 60}s")
            return True

        # Progress indicator
        now = time.time()
        if now - last_dot >= 30:
            elapsed = int(now - start)
            print(f"  ... still running ({elapsed // 60}m {elapsed % 60}s elapsed)")
            last_dot = now

        time.sleep(5)

    print(f"\n  [TIMEOUT] Backtest exceeded {timeout_minutes} minute limit.")
    return False


def launch_backtest(
    terminal_path: Path,
    config_path: Path,
) -> bool:
    """
    Launch MT5 in Strategy Tester mode with the given config.
    MT5 CLI: terminal64.exe /config:path_to_config.ini
    """
    if is_mt5_running():
        print("  [WARNING] MT5 is already running.")
        print("  Please close it first, then re-run this script.")
        print("  (Auto-closing in 10 seconds...)")
        # Try to close gracefully
        try:
            subprocess.run(["taskkill", "/IM", "terminal64.exe"], timeout=10)
            time.sleep(5)
        except Exception:
            pass

        if is_mt5_running():
            print("  [ERROR] Could not close MT5. Please close it manually.")
            return False

    cmd = [str(terminal_path), f"/config:{config_path}"]
    print(f"  Launching: {' '.join(cmd)}")

    try:
        # Use Popen (non-blocking) since MT5 runs independently
        process = subprocess.Popen(
            cmd,
            cwd=str(terminal_path.parent),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        print(f"  [OK] MT5 launched (PID: {process.pid})")
        return True

    except FileNotFoundError:
        print(f"  [ERROR] Terminal not found: {terminal_path}")
        return False
    except Exception as e:
        print(f"  [ERROR] Failed to launch MT5: {e}")
        return False


def run_backtest(
    terminal_path: Path,
    data_path: Path,
    config_template: Path,
    login: str = "0",
    password: str = "",
    server: str = "Deriv-Demo",
    symbol: str = "XAUUSD",
    from_date: str = None,
    to_date: str = None,
    deposit: int = 10000,
    leverage: int = 100,
    timeout_minutes: int = 120,
) -> dict:
    """
    Complete backtest pipeline:
    1. Generate tester config
    2. Clean old reports
    3. Launch MT5
    4. Wait for completion
    5. Find and return report files
    """
    print("\n[STEP 5] Preparing backtest configuration...")

    config_path = data_path / "tester" / "CLAWBOT_tester.ini"
    generate_tester_config(
        config_template=config_template,
        output_path=config_path,
        login=login,
        password=password,
        server=server,
        symbol=symbol,
        from_date=from_date,
        to_date=to_date,
        deposit=deposit,
        leverage=leverage,
    )
    print(f"  [OK] Tester config written: {config_path}")

    print("\n[STEP 6] Cleaning old reports...")
    clean_old_reports(data_path)

    print("\n[STEP 7] Launching MT5 Strategy Tester...")
    if not launch_backtest(terminal_path, config_path):
        return None

    print("\n[STEP 8] Waiting for backtest completion...")
    completed = wait_for_mt5_close(timeout_minutes)

    if not completed:
        print("  Checking for partial results...")

    # Allow files to flush
    time.sleep(3)

    print("\n[STEP 9] Searching for results...")
    reports = find_report_files(data_path)

    if reports:
        print(f"  [OK] Found {len(reports)} report file(s):")
        for key, path in reports.items():
            print(f"    - {key}: {path.name}")
    else:
        print("  [WARNING] No report files found.")
        print("  The backtest may not have completed successfully.")
        print("  Check MT5 Journal tab for errors.")

    return reports


def parse_mt5_html_report(report_path: Path) -> dict:
    """
    Parse the MT5-generated HTML backtest report.
    Extracts key metrics: total trades, win rate, profit factor, drawdown.
    This is a fallback if the EA's CSV audit report is not available.
    """
    if not report_path.exists():
        return None

    try:
        content = report_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return None

    metrics = {}

    # Simple parsing of MT5 HTML report table rows
    import re

    # Total Net Profit
    match = re.search(r'Total Net Profit.*?>([-\d\s.]+)<', content)
    if match:
        metrics["net_profit"] = float(match.group(1).replace(" ", ""))

    # Total Trades
    match = re.search(r'Total Trades.*?>(\d+)<', content)
    if match:
        metrics["total_trades"] = int(match.group(1))

    # Profit Factor
    match = re.search(r'Profit Factor.*?>([\d.]+)<', content)
    if match:
        metrics["profit_factor"] = float(match.group(1))

    # Maximal Drawdown (%)
    match = re.search(r'Maximal Drawdown.*?>([\d.]+)%', content)
    if match:
        metrics["max_drawdown_pct"] = float(match.group(1))

    # Win trades / Total trades -> win rate
    match = re.search(r'Profit Trades.*?>(\d+).*?of total.*?>([\d.]+)%', content, re.DOTALL)
    if match:
        metrics["win_trades"] = int(match.group(1))
        metrics["win_rate"] = float(match.group(2))
    elif "total_trades" in metrics:
        # Try alternative pattern
        match = re.search(r'Short Trades \(won %\).*?>(\d+).*?([\d.]+)%', content, re.DOTALL)
        match2 = re.search(r'Long Trades \(won %\).*?>(\d+).*?([\d.]+)%', content, re.DOTALL)
        if match and match2:
            short_total = int(match.group(1))
            short_win_pct = float(match.group(2))
            long_total = int(match2.group(1))
            long_win_pct = float(match2.group(2))
            total = short_total + long_total
            if total > 0:
                wins = int(short_total * short_win_pct / 100) + int(long_total * long_win_pct / 100)
                metrics["win_rate"] = (wins / total) * 100
                metrics["win_trades"] = wins

    # Sharpe Ratio
    match = re.search(r'Sharpe Ratio.*?>([-\d.]+)<', content)
    if match:
        metrics["sharpe_ratio"] = float(match.group(1))

    return metrics if metrics else None
